<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppHttpOdmDocumentsFotoAutoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['filename'])) {
            $value = $data['filename'];
            $return = (string) $value;
            $this->class->reflFields['filename']->setValue($document, $return);
            $hydratedData['filename'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['selected'])) {
            $value = $data['selected'];
            $return = (bool) $value;
            $this->class->reflFields['selected']->setValue($document, $return);
            $hydratedData['selected'] = $return;
        }
        return $hydratedData;
    }
}